# apiVersion: v1
# kind: ConfigMap
# metadata: 
#   name: mariadb-config
# data: 
#   MYSQL_DATABASE: example
#   MYSQL_ROOT_PASSWORD: db-q5n2g

# ---

apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  ports:
    - port: 3306
  selector:
    app: mariadb
  clusterIP: None

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - image: mariadb:10-focal
          name: mariadb
          # envFrom:
          #   - configMapRef:
          #     name: mariadb-config
          env:
            - name: MYSQL_DATABASE
              value: example
            - name: MYSQL_ROOT_PASSWORD
              value: db-q5n2g # TODO : Transform into file
          ports:
            - containerPort: 3306
              name: mariadb
          volumeMounts:
            - name: mariadb-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: mariadb-claim
        - name: mariadb-storage-secret