apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |-
    server {
      listen       80;
      server_name  localhost;
      location / {
          # proxy_pass          http://backend:8000;
          # proxy_http_version  1.1;
      }
    }

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: nginx-pod-storage
          configMap:
            name: nginx-config
            items:
              - key: default.conf
                path: default.conf
      containers:
        - name: nginx
          image: nginx:latest
          # command: ["/bin/sh"]
          # args: [ "-c", "while true; do sleep 100000; done"]
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/etc/nginx/conf.d"
              name: nginx-pod-storage